### ISSUE TITLE
Incorrect parsing of "mixed" quotes

### ISSUE THREAD

**Issue by fixator10** [Tobotimus/redgettext#1]
so, i have this code:
`_('"days" arg cannot be less than 1...')`

in .pot file generated by redgettext it looks like this:
```pot
msgid "\\\"days\\\" arg cannot be less than 1..."
msgstr ""
```

With default pygettext, however, everything is ok
```pot
msgid "\"days\" arg cannot be less than 1..."
msgstr ""
```

**Comment by Tobotimus** [comment]
Hmm, it seems [polib](https://polib.readthedocs.io/en/latest/index.html) is escaping the msgids under the hood, whilst I am escaping it explicitly, causing them to be escaped twice:

Line 196 of redgettext.py:
```py
            self.__cur_potfile.append(
                polib.POEntry(
                    msgid=polib.escape(msg),
                    occurrences=[occurrence],
                    flags=flags,
                )
            )
```
